// Generated by CoffeeScript 1.6.2
(function() {
  var listMainClause, listString, pollute, stringList,
    __slice = [].slice;

  listString = require('./listString');

  stringList = require('./stringList');

  listMainClause = require('./listMainClause');

  pollute = function() {
    Object.defineProperty(Array.prototype, "listString", {
      value: function() {
        var args;

        args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        return listString.apply(null, [this].concat(args));
      }
    });
    return Object.defineProperty(String.prototype, "stringList", {
      value: function() {
        var args;

        args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        return stringList.apply(null, [this].concat(args));
      }
    });
  };

  module.exports = {
    listString: listString,
    stringList: stringList,
    listMainClause: listMainClause,
    pollute: pollute
  };

  if (module.parent == null) {
    pollute();
    console.log("1, 2, 3, 5-10".stringList());
    console.log([1, 2, 3, 4, 5, 10, 11, 15].listString());
  }

}).call(this);
