// Generated by CoffeeScript 1.6.2
(function() {
  var NounInflector, PresentVerbInflector, listMainClause, listString, nounInflector, pluralize, verbInflector;

  pluralize = require('pluralize');

  NounInflector = require('natural/lib/natural/inflectors/noun_inflector');

  PresentVerbInflector = require('natural/lib/natural/inflectors/present_verb_inflector');

  nounInflector = new NounInflector();

  verbInflector = new PresentVerbInflector();

  listString = require('./listString');

  listMainClause = function(list, noun, verb, options) {
    var cmd;

    if (noun == null) {
      noun = '';
    }
    if (options == null) {
      options = {};
    }
    cmd = list.length > 1 ? 'pluralize' : 'singularize';
    if (verb != null) {
      return "" + (nounInflector[cmd](noun)) + " " + (listString(list)) + " " + (verbInflector[cmd](verb));
    } else {
      return "" + (nounInflector[cmd](noun)) + " " + (listString(list));
    }
  };

  module.exports = listMainClause;

  if (module.parent == null) {
    console.log(listMainClause([1], "Claim", 'claim'));
    console.log(listMainClause([1, 3, 5], "Claim", 'claim'));
    console.log(listMainClause([1, 3, 5], "Claim"));
    console.log(verbInflector.pluralize('run'));
    console.log(verbInflector.singularize('run'));
  }

}).call(this);
