// Generated by CoffeeScript 1.9.1
(function() {
  var Articles, any, arr, consolidateAlphaRanges, consolidateRanges, every, i, isInt, isNumber, j, listString, ref, results, test, toString, unique, x;

  ref = require('./utils'), isNumber = ref.isNumber, isInt = ref.isInt, unique = ref.unique, consolidateRanges = ref.consolidateRanges, consolidateAlphaRanges = ref.consolidateAlphaRanges, every = ref.every, any = ref.any;

  Articles = require('articles');

  toString = Object.prototype.toString;

  listString = function(me, options) {
    var a, andOrProvided, andor, arr, article, comma, complex, delimiter, isRange, item, ref1, ref2, ref3, ref4;
    if (options == null) {
      options = {};
    }
    if (toString.call(options) === '[object String]') {
      andor = options;
      options = {
        article: arguments[2],
        comma: arguments[3]
      };
    } else {
      andor = (ref1 = (ref2 = options.andor) != null ? ref2 : options.conjunction) != null ? ref1 : 'and';
    }
    andOrProvided = (andor != null ? andor.length : void 0) > 0;
    article = options.article;
    comma = (ref3 = (ref4 = options.comma) != null ? ref4 : options.separator) != null ? ref3 : ', ';
    isRange = every(me, isInt);
    if (isRange) {
      arr = consolidateRanges((function() {
        var j, len, results;
        results = [];
        for (j = 0, len = me.length; j < len; j++) {
          a = me[j];
          results.push(parseInt(a));
        }
        return results;
      })());
    } else {
      isRange = every(me, function(item) {
        return /^[a-z]$/i.test(item);
      });
      if (isRange) {
        arr = consolidateAlphaRanges(me);
      }
    }
    if (me.length > 2) {
      if (isRange) {
        if (arr.length > 2) {
          delimiter = comma;
        }
      } else {
        complex = any(me, function(item) {
          return /,/.test(item);
        });
        delimiter = complex ? '; ' : comma;
      }
    }
    if (delimiter == null) {
      delimiter = andOrProvided ? andor : '';
      if (/^[\w\/]+$/i.test(delimiter)) {
        delimiter = " " + delimiter + " ";
      }
    }
    if (arr == null) {
      arr = me.slice(0);
    }
    if (/^an?$/.test(article)) {
      arr = (function() {
        var j, len, results;
        results = [];
        for (j = 0, len = arr.length; j < len; j++) {
          item = arr[j];
          results.push(Articles.articlize(item));
        }
        return results;
      })();
    } else if ((article != null ? article.length : void 0) > 0) {
      arr = (function() {
        var j, len, results;
        results = [];
        for (j = 0, len = arr.length; j < len; j++) {
          item = arr[j];
          results.push(article + " " + item);
        }
        return results;
      })();
    }
    if (andOrProvided && (arr.length > 2)) {
      arr.push(andor + " " + (arr.pop()));
    }
    return arr.join(delimiter);
  };

  module.exports = listString;

  if (require.main === module) {
    test = function(item) {
      return /\d/.test(item);
    };
    arr = (function() {
      results = [];
      for (j = 1; j <= 1000; j++){ results.push(j); }
      return results;
    }).apply(this);
    console.time('every');
    x = (function() {
      var k, results1;
      results1 = [];
      for (i = k = 1; k <= 1000; i = ++k) {
        results1.push(arr.every(test));
      }
      return results1;
    })();
    console.timeEnd('every');
    console.time('myevery');
    x = (function() {
      var k, results1;
      results1 = [];
      for (i = k = 1; k <= 1000; i = ++k) {
        results1.push(every(arr, test));
      }
      return results1;
    })();
    console.timeEnd('myevery');
  }

}).call(this);
