// Generated by CoffeeScript 1.10.0
(function() {
  var stringList,
    indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  stringList = function(me, options) {
    var endNum, num, numbers, pat, ref, ref1, ref2, ref3, res, sort, unique;
    if (options == null) {
      options = {};
    }
    sort = (ref = options.sort) != null ? ref : true;
    unique = (ref1 = options.unique) != null ? ref1 : true;
    numbers = [];
    pat = /(\d+)(?:\s*[-—]\s*(\d+))?/g;
    while ((res = pat.exec(me))) {
      num = parseInt(res[1]);
      endNum = parseInt((ref2 = res[2]) != null ? ref2 : num);
      if (endNum < num) {
        ref3 = [num, endNum], endNum = ref3[0], num = ref3[1];
      }
      while (num <= endNum) {
        if (!(unique && (indexOf.call(numbers, num) >= 0))) {
          numbers.push(num);
        }
        num++;
      }
    }
    if (sort) {
      numbers.sort(function(a, b) {
        return a - b;
      });
    }
    return numbers;
  };

  module.exports = stringList;

}).call(this);
