// Generated by CoffeeScript 1.6.2
(function() {
  var arr, i, out, str, stringList,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  stringList = function(me, options) {
    var endNum, num, numbers, pat, res, sort, unique, _ref, _ref1, _ref2, _ref3;

    if (options == null) {
      options = {};
    }
    sort = (_ref = options.sort) != null ? _ref : true;
    unique = (_ref1 = options.unique) != null ? _ref1 : true;
    numbers = [];
    pat = /(\d+)(?:\s*[-—]\s*(\d+))?/g;
    while ((res = pat.exec(me))) {
      num = parseInt(res[1]);
      endNum = parseInt((_ref2 = res[2]) != null ? _ref2 : num);
      if (endNum < num) {
        _ref3 = [num, endNum], endNum = _ref3[0], num = _ref3[1];
      }
      while (num <= endNum) {
        if (!(unique && (__indexOf.call(numbers, num) >= 0))) {
          numbers.push(num);
        }
        num++;
      }
    }
    if (sort) {
      numbers.sort(function(a, b) {
        return a - b;
      });
    }
    return numbers;
  };

  module.exports = stringList;

  if (module.parent == null) {
    arr = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10].concat([5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]);
    arr.sort(function() {
      return Math.random();
    });
    str = arr.join(', ') + ', 15-20';
    console.log(str);
    console.time("iter");
    i = 0;
    while (i++ < 1000) {
      out = stringList(str, {
        unique: false
      });
    }
    console.timeEnd('iter');
  }

}).call(this);
